/**
 * This is simple calculator. It makes the basic arithmetic operations.
 * It accepts inputs through the key-buttons and the keyboard. 
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import view.Click;
/**
 * @author Ricardo Saumeth.
 * @version 26/05/2014
 */
public class CalculatorGUI extends javax.swing.JFrame {
    //instance field of the interface 
    private OperationsListener listener;
    //variables to make the operations
    double firstNumber = 0, secondNumber = 0, result = 0;
    //variable to define the arithmetic operation
    Click operation;
    /**
     * Creates new form CalculatorGUI.
     * Adds listener to the buttons to make the operations.
     */
    public CalculatorGUI() {
        initComponents();
        lookAndFeel();
        
        plusButton.addActionListener(new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent ae) {
            addFirstNumber();
            operation = Click.addition;
            display("");
         }
        });
        
        minusButton.addActionListener(new ActionListener() {
         @Override
            public void actionPerformed(ActionEvent ae) {
              addFirstNumber();
              operation = Click.subtraction;
              display(""); 
            }
        });
        multiplyButton.addActionListener(new ActionListener() {
         @Override
            public void actionPerformed(ActionEvent ae) {
              addFirstNumber();
              operation = Click.multiplication;
              display(""); 
            }
        });
        divisionButton.addActionListener(new ActionListener() {
         @Override
           public void actionPerformed(ActionEvent ae) {
              addFirstNumber();
              operation = Click.division;
              display("");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        doubleZeroButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        posneg = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        displayField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                displayFieldKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        fourButton.setText("4");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        doubleZeroButton.setText("00");
        doubleZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleZeroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(oneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(threeButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fourButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sixButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sevenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eightButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nineButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(zeroButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doubleZeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {eightButton, fiveButton, fourButton, nineButton, oneButton, sevenButton, sixButton, threeButton, twoButton, zeroButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneButton)
                    .addComponent(twoButton)
                    .addComponent(threeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourButton)
                    .addComponent(fiveButton)
                    .addComponent(sixButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenButton)
                    .addComponent(eightButton)
                    .addComponent(nineButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroButton)
                    .addComponent(doubleZeroButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {eightButton, fiveButton, fourButton, nineButton, oneButton, sevenButton, sixButton, threeButton, twoButton, zeroButton});

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        plusButton.setText("+");

        minusButton.setText("-");

        decimalButton.setText(".");
        decimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalButtonActionPerformed(evt);
            }
        });

        multiplyButton.setText("*");

        divisionButton.setText("/");

        equalsButton.setText("=");
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        posneg.setText("+/-");
        posneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posnegActionPerformed(evt);
            }
        });

        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(plusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divisionButton)
                            .addComponent(multiplyButton)
                            .addComponent(minusButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posneg)
                            .addComponent(clearButton)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(decimalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalsButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {decimalButton, divisionButton, equalsButton, minusButton, multiplyButton, plusButton});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clearButton, posneg});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minusButton)
                            .addComponent(clearButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multiplyButton)
                            .addComponent(posneg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimalButton)
                    .addComponent(equalsButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    * Clear the screen and reset the variable to zero;
    */
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
        
    }//GEN-LAST:event_clearButtonActionPerformed
    /**
    * Display the number 1 on the screen.
    */
    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        displayField.setText(displayField.getText() + oneButton.getText());
    }//GEN-LAST:event_oneButtonActionPerformed
    /**
    *Display the number 2 on the screen.
    */
    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        displayField.setText(displayField.getText() + twoButton.getText());
    }//GEN-LAST:event_twoButtonActionPerformed
    /**
    * Display the number 3 on the screen.
    */ 
    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        displayField.setText(displayField.getText() + threeButton.getText());
    }//GEN-LAST:event_threeButtonActionPerformed
    /**
    * Display the number 4 on the screen.
    */
    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
       displayField.setText(displayField.getText() + fourButton.getText()); 
    }//GEN-LAST:event_fourButtonActionPerformed
    /**
    * Display the number 5 on the screen.
    */ 
    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        displayField.setText(displayField.getText() + fiveButton.getText());
    }//GEN-LAST:event_fiveButtonActionPerformed
    /**
    * Display the number 6 on the screen.
    */
    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        displayField.setText(displayField.getText() + sixButton.getText());
    }//GEN-LAST:event_sixButtonActionPerformed
    /**
    * Display the number 7 on the screen.
    */
    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        displayField.setText(displayField.getText() + sevenButton.getText());
    }//GEN-LAST:event_sevenButtonActionPerformed
    /**
    * Display the number 8 on the screen.
    */
    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        displayField.setText(displayField.getText() + eightButton.getText());
    }//GEN-LAST:event_eightButtonActionPerformed
    /**
    * Display the number 9 on the screen.
    */
    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        displayField.setText(displayField.getText() + nineButton.getText());
    }//GEN-LAST:event_nineButtonActionPerformed
    /**
    * Display the number 0 on the screen.
    */
    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        displayField.setText(displayField.getText() + zeroButton.getText());
    }//GEN-LAST:event_zeroButtonActionPerformed
    /**
    * Display the number 00 on the screen.
    */
    private void doubleZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleZeroButtonActionPerformed
        displayField.setText(displayField.getText() + doubleZeroButton.getText());
    }//GEN-LAST:event_doubleZeroButtonActionPerformed

   /**
    * Display decimal point on the screen
    */
    private void decimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalButtonActionPerformed
        displayField.setText(displayField.getText() + decimalButton.getText());
    }//GEN-LAST:event_decimalButtonActionPerformed

   
   /**
    * Invoke equals method. 
    */
    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        equals();
    }//GEN-LAST:event_equalsButtonActionPerformed
    /**
    * Change the sign of a number. From positive to negative and vice-versa.
    */
    private void posnegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posnegActionPerformed
        addFirstNumber();
        firstNumber = firstNumber * (-1);
        display(String.valueOf(firstNumber));
    }//GEN-LAST:event_posnegActionPerformed
   /**
    * Determines with key was pressed according to the arithmetic operations.
    */
    private void displayFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayFieldKeyPressed
        switch(evt.getKeyCode()){
            
            case KeyEvent.VK_ENTER:
                equals();
                break;
            case KeyEvent.VK_ADD:
                addFirstNumber();
                break;
            case KeyEvent.VK_SUBTRACT:
                addFirstNumber();
                break;
            case KeyEvent.VK_MULTIPLY:
                addFirstNumber();
                break; 
            case KeyEvent.VK_DIVIDE:
                addFirstNumber();
                break;
        }
        
    }//GEN-LAST:event_displayFieldKeyPressed
    /**
     * Stores the first number input
     * @throws NumberFormatException 
     */
    private void addFirstNumber() throws NumberFormatException {
        firstNumber = Double.parseDouble(displayField.getText());
    }
    /**
    * Set the second variable to the second number entered.
    * Processes the operations and invoke the display method
    */
    private void equals() throws NumberFormatException {
        secondNumber = Double.parseDouble(displayField.getText());
        fireNumbersEvent(new NumbersFormEvent(firstNumber, secondNumber, operation));
        
    }
    /**
     * Fires the method of the interface overrode by the controller. 
     * @param evt 
     */
    private void fireNumbersEvent(NumbersFormEvent evt){
        if(listener != null){
            listener.makeOperations(evt);
        }
    }
    /**
    * Allows to input numbers using the numeric keypad.
    */
    private void displayFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayFieldKeyReleased
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ADD:
                display("");
                operation = Click.addition;
                break;
        case KeyEvent.VK_SUBTRACT:
                display("");
                operation = Click.subtraction;
                break;
        case KeyEvent.VK_MULTIPLY:
                display("");
                operation = Click.multiplication;
                break; 
            case KeyEvent.VK_DIVIDE:
                display("");
                operation = Click.division;
                break;
            case KeyEvent.VK_BACK_SPACE:
                clear();
                break;
    }//GEN-LAST:event_displayFieldKeyReleased
} 
    /**
    * Reset the variables. Display zero on the textField
    */
    private void clear() {
        displayField.setText("");
        firstNumber = 0;
        secondNumber = 0;
    }
        
    /**
    * Display the numbers on the textField
    * @param answer Receives the number to be displayed
    */
    public void display(String answer) {
        displayField.setText(answer);
    }
    /**
     * Sets the object listener of the interface. It allows the controller to 
     * override the interface method.
     * @param listener 
     */
    public void addOperationListener(OperationsListener listener) {
        this.listener = listener;
    }

    
//    public void displayErrorMessage(String error) {
//        JOptionPane.showMessageDialog(this, error, "Input not valid", 
//                JOptionPane.ERROR_MESSAGE);
//    }
        
    /**
     * Sets the look and feel of the GUI
     */
    private final void lookAndFeel() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setVisible(true);

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JTextField displayField;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton doubleZeroButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton posneg;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
